### PR TITLE
Added d3tree3

### PR DESCRIPTION
**Pull request by lmccusker**
I added a third option - `d3tree3`.

`d3tree3` works almost identical to `d3tree2` with the following exceptions:
- Styles have been changed a bit to mimic `gvisTreeMap` in the `googleVis` library more
- Scale has been moved to top and is now a smooth a color gradient
- On hover, a triangle appears on the legend to show the color value, as well as the number
- If the `stdErr` option is used in the `treemap` function, a grey rectangle indicating the confidence interval will appear along with the triangle on hover

See the simple example below.  The standard error is arbitrary, but you can get the idea.

```
data(business)
business$employees.growth <- business$employees - business$employees.prev
business$employees.se <- abs(business$employees.growth / business$employees.prev) * 10000

tm <- 
  treemap(business,
          index=c("NACE1", "NACE2"),
          stdErr="employees.se",
          tooltipLabels=c("Turnover"),
          tooltipValues=c("turnover"),
          vSize="employees",
          vColor="employees.growth",
          type="value",
          palette="BrBG",
          range=c(-10000,30000),
          fun="mean")

d3tree3( tm, rootname = "World" )
```

And the result, with mouse hovered over "H":
image

### CODE REVIEW

**Comment by ignacio82** [comment]
:+1:

**Comment by timelyportfolio** [comment]
@lmccusker very nice.  I really appreciate the contribution.  One thing, why the change to `d3tree2.css`?

**Comment by lmccusker** [comment]
Oops, those are unnecessary.  I got the two css files crossed at one point and wasn't thorough in reverting it.

Sorry!

**Comment by timelyportfolio** [comment]
@lmccusker does `d3tree3` work for you in RStudio Viewer?  The legend fails in RStudio Viewer for me, but it works fine with Chrome and Firefox.  The `select` for `arrayOfRects` returns nothing even after the `innerHTML` has run.  I'm trying to work around it with no luck so far.

**Comment by lmccusker** [comment]
I have only used it in the web browser, but I think @ignacio82 may have had success using it in the RStudio Viewer.

I hadn't realized the RStudio Viewer had developer tools - I should be able to fix the issue. Stay tuned.

**Comment by ignacio82** [comment]
It works on Rstudio server and also as a shiny app on a free shiny server.
It does not work on Rstudio on a Windows computer.

**Pull request merged**
